POST http://localhost:3333/habits
Content-Type: application/json

{
  "title": "Beber agua",
  "weekDays": [0, 1, 2, 3]
}

###
GET http://localhost:3333/day?date=2024-02-13T00:00:00.000z
Content-Type: application/json

###
PATCH http://localhost:3333/habits/ee61799e-3527-494b-911c-0b7eb87d0245/toggle

###
GET http://localhost:3333/summary
